// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCheckHistory = "check_historys"

// CheckHistory mapped from table <check_historys>
type CheckHistory struct {
	ID        int64      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	DonodeID  *int64     `gorm:"column:donode_id;type:int" json:"donode_id"`
	NodeID    *int64     `gorm:"column:node_id;type:int" json:"node_id"`
	IP        *string    `gorm:"column:ip;type:varchar(50)" json:"ip"`
	PingLong  *float32   `gorm:"column:ping_long;type:float" json:"ping_long"`
	NodeLong  *float32   `gorm:"column:node_long;type:float" json:"node_long"`
	APILong   *float32   `gorm:"column:api_long;type:float" json:"api_long"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;unsigned:autoUpdateTime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;unsigned:autoUpdateTime" json:"updated_at"`
}

// TableName CheckHistory's table name
func (*CheckHistory) TableName() string {
	return TableNameCheckHistory
}
