// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDocheckNode = "docheck_nodes"

// DocheckNode mapped from table <docheck_nodes>
type DocheckNode struct {
	ID        int64      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name      *string    `gorm:"column:name;type:varchar(255)" json:"name"`
	IP        *string    `gorm:"column:ip;type:varchar(100)" json:"ip"`
	City      *string    `gorm:"column:city;type:varchar(100)" json:"city"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;unsigned:autoUpdateTime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;unsigned:autoUpdateTime" json:"updated_at"`
}

// TableName DocheckNode's table name
func (*DocheckNode) TableName() string {
	return TableNameDocheckNode
}
